/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class asus_model_utils_JniUtil */

#ifndef _Included_asus_model_utils_JniUtil
#define _Included_asus_model_utils_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     asus_model_utils_JniUtil
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_asus_model_utils_JniUtil_getStringFromC
  (JNIEnv *env, jclass jc);

JNIEXPORT jstring JNICALL Java_asus_model_utils_JniUtil_getStringFromC2
        (JNIEnv *env, jclass jc);


#ifdef __cplusplus
}
#endif
#endif
